name: Deploy to staging

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing stork
        run: cargo install stork-search
      - name: Building search index
        run: |
          ./scripts/build-search-index.sh
          git config user.name "$(git log --format='%an' HEAD^!)"
          git config user.email "$(git log --format='%ae' HEAD^!)"
          git add .
          git commit -m "Build search index"
          git push
      - name: Deploying preview on Vercel
        run: yarn deploy --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
