name: Deploy to Production

on:
  push:
    branches:
      - 'main'

jobs:
  setup:
    name: Setup deployment environment
    runs-on: ubuntu-latest
    steps:
      - name: Installing node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

  deploy-production:
    name: Deploy production
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v2 # Get last commit pushed
      - name: Deploying on Vercel
        run: yarn deploy:prod --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
