name: Deploy to staging

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  deploy-staging:
    name: Deploy to staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploying preview on Vercel
        run: yarn deploy --token $VERCEL_TOKEN
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
